repos:
- repo: local
  hooks:
    - id: system
      name: black
      entry: poetry run black .
      pass_filenames: false
      language: system
#    - id: system
#      name: isort
#      entry: poetry run isort .
#      pass_filenames: false
#      language: system
#    - id: system
#      name: pylint
#      entry: poetry run pylint --load-plugins pylint_django --django-settings-module=blackslope.settings apiapp
#      pass_filenames: false
#      language: system
#    - id: system
#      name: pytest
#      entry: poetry run pytest
#      pass_filenames: false
#      language: system