name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: install poetry 
      uses: Gr1N/setup-poetry@v7
      with:
        poetry-version: 1.1.12
    
    - name: install dependencies 
      run: |
        poetry install

    - name: Test with pytest
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        poetry run pytest -vv
